backend:
  name: test-repo
  # branch: develop # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
media_folder: "src/img/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "img/uploads"

media_library:
  name: cloudinary
  config:
    cloud_name: waxflower-bridal
    api_key: 835527866354169
    output_filename_only: true

collections:
  - label: "Home"
    name: "home"
    files:
      - name: "home" # Used in routes, e.g., /admin/collections/blog
        label: "Home" # Used in the UI
        file: "src/html/pages/index" # The path to the folder where the documents are stored
        create: false # Allow users to create new documents in this collection
        slug: "{{slug}}" # Filename
        extension: "html"
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Carousel", name: "carouselImages", widget: "list", field: {label: Image, name: image, widget: image}}