dev_server:
  domain: localhost
  port: 3001
  back: false

paths:
  dist: dist

  html:
    watch:
      pages: src/html/{data,helpers,pages}/**/*
      reset: src/html/{layouts,partials}/**/*.html

    src: src/html/pages/**/*.{html,hbs,handlebars}
    root: src/html/pages/
    layouts: src/html/layouts/
    partials: src/html/partials/
    data: src/html/data/
    helpers: src/html/helpers/

  css:
    watch: src/css/**/*.scss
    entry:
      - src/css/main.scss
      - src/css/landing.scss
    include:
      - node_modules

  js:
    watch: src/js/**/*.js
    entry:
      - src/js/main.js
      - src/js/fonts.js
    include:
      - node_modules
      - src/js/lib
    exclude_loaders:
      - node_modules

  img:
    watch: src/img/**/*
    include: src/img/**/*
    output_dir: img

  fonts:
    watch: src/fonts/**/*
    include:
      - src/fonts/**/*
    output_dir: webfonts

  admin:
    watch: src/admin/**/*
    include:
      - src/admin/**/*
    output_dir: admin

  etc:
    - src/etc/**/*

  backend:
    - ../back/**/*.html*
    - ../back/**/*.{php,rb,js,yml}

autoprefixer_compatibility:
  - last 3 versions
  - ie >= 9
  - ios >= 7
